# Generated by Django 3.2 on 2021-05-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produc_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('pubg_date', models.DateField()),
            ],
        ),
    ]
