# Generated by Django 3.2 on 2021-05-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210507_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pubg_date',
            new_name='pub_date',
        ),
    ]
